### ISSUE TITLE
Update this fork

### ISSUE THREAD

**Issue by thejpster** [rust-embedded-community/tm4c-rs#3]
We forked this due to upstream issues. @eldruin please can we replicate recent changes here?

**Comment by eldruin** [comment]
Will do. Sorry, I forgot we already had a fork.

**Comment by whitequark** [comment]
Could you also update the repository metadata on crates.io?

**Comment by thejpster** [comment]
Which I think comes from the repository field in this crate's Cargo.toml? Is it auto generated?

**Comment by whitequark** [comment]
No I think it's just a normal file. Editing https://github.com/rust-embedded-community/tm4c-rs/blob/master/crates/tm4c123x/Cargo.toml and https://github.com/rust-embedded-community/tm4c-rs/blob/master/crates/tm4c129x/Cargo.toml should be enough

**Comment by eldruin** [comment]
I just published version 0.9.2 of both crates [tm4c123x](https://crates.io/crates/tm4c123x) and [tm4c129x](https://crates.io/crates/tm4c129x). Closing.
